### ISSUE TITLE
Doesn't handle `(require ...)` properly

### ISSUE THREAD

**Issue by halgari** [weavejester/ns-tracker#19]
Some old code uses the ns form `(ns foo (require [bar]))` since that isn't the the keyword `:require` ns-tracker will silently fail on these files. Can we either warn the user or error, or perhaps just handle the cases where we find a `require` or a `use` symbol?

Location of the check:
https://github.com/weavejester/ns-tracker/blob/master/src/ns_tracker/nsdeps.clj#L21

**Comment by weavejester** [comment]
The `(ns foo (require [bar]))` form has never been correct to my knowledge, so the most appropriate thing to do here is to throw an error, or perhaps raise a warning. But I'm not sure it's ns-tracker's job to raise warnings on bad code, that seems more like the job of a linter.
